version: '1.0'
name: pipeline-docker
displayName: pipeline-docker
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-6d1e3d31
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: ccr.ccs.tencentyun.com/hypsinoia/odoo15-python312
        username: '100039322638'
        password: i3ZY9.Wc_wkhSft
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
