name: Build and Push to GitHub and Tencent Cloud

on:
  push:
    branches: [ "main" ]

env:
  GH_REGISTRY: ghcr.io
  TENCENT_REGISTRY: ccr.ccs.tencentyun.com
  NAMESPACE: hypsinoia
  IMAGE_NAME: odoo15-python312

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 登录腾讯云容器镜像服务
      - name: Log in to Tencent Cloud TCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.TENCENT_REGISTRY }}
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          password: ${{ secrets.TENCENT_CLOUD_PASSWORD }}

      # 构建并推送镜像到两个仓库
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.TENCENT_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.TENCENT_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}